stages:
  - build
  - deploy

build dentalclinic-frontend:
  stage: build
  only:
    refs:
      - main
  tags:
    - main
  script:
    - docker build -t dentalclinic-frontend .

deploy dentalclinic-frontend:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - main
  script:
    - cd /opt/dentalclinic-frontend
    - docker compose down
    - docker compose up -d
